version: '3.7'

services:
  django:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/static
    expose:
        - 8000
    env_file: env/settings.prod.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1
    volumes:
      - db:/var/lib/postgresql/data
    env_file: env/postgres.prod.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
    ports:
      - 1337:80
    depends_on:
      - django

volumes:
  db:
  static_volume:
